### PR TITLE
Added and fixed a few filters.

### PR DESCRIPTION
**Pull request by drws**
I added a few missing filters from my AdBlock list. The list was also sorted which produced all that removals and additions.

### CODE REVIEW

**Comment by betterwebleon** [comment]
Great, thanks!

It seems however the following rule is not needed:
`@@||podcrto.si`

And if I'm not mistaken, these filters are obsolete:
`fotoarhiv.si###hi-eu-opt-in`
`najsplet.com^$third-party`
`obisk.net^$third-party`
`||over.net###askcook`
`pagerank.si^$third-party`
`stevec.si^$third-party`

Webpage http://nasmehni.me/ seems to be down as well.

**Comment by drws** [comment]
While I can agree with other sites being down I still find the rules `obisk.net^$third-party` and `||over.net###askcook` necessary. The second one is not needed on the main over.net site, but on its subdomains, such as med.over.net, where the cookie notice is shown.

**Comment by betterwebleon** [comment]
Regional lists normally don't cover cookie notifications, neither does Slovenian list. In fact it is much faster and more efficient to block them with separated addon, which is also not limited to regional (Slovenian) websites. Recommended addon is **I don't care about cookies**:
- for Firefox, install it from [Addons Mozilla (AMO)](https://addons.mozilla.org/firefox/addon/i-dont-care-about-cookies/).
- for Chrome, install it from [Chrome Web Store](https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja).
- for Opera, install it from [Opera Add Ons](https://addons.opera.com/extensions/details/i-dont-care-about-cookies/).
- for Pale Moon, install it from [Pale Moon Extensions](https://addons.palemoon.org/extensions/other/i-dont-care-about-cookies/).

If you still want to use cookie notification filter list in your content-blocker instead of separated add-on (**not recommended**), you can add a custom filter list.
In uBlock Origin, you can copy and paste the following link to custom filter list (in "_3rd-party filters_" tab):
`http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/`

As regards all other websites, I try to avoid "third-party" rules, because they are often too broad. For the specific website (http://www.obisk.net/) the necessary cosmetic rules have already been added.
In this case, the remaining (tracking and advertising) is taken care by _EasyList_ and _Fanboy's Enhanced Tracking List_. These rules are not duplicated in Slovenian list.

It is therefore recommended to add further filter lists to your content-blocker (along with configuring some other settings) to optimize filtering, as it is thoroughly described **[here](https://github.com/betterwebleon/international-list#2-recommended-content-filtering-software)**.

I hope this helps.

**Comment by drws** [comment]
Thank you, I didn't know about the I don't care about cookies addon and have already started using it, but I see there are still a few cookie-related filters on the SVN list:

`||mercator.si/cookiesdirective/js/iCD.min.js`
`citymagazine.si###content > .wrapper > .cookie-bar`
`sta.si##.cookiepanel`
`www.gorenjski-muzej.si##.pea_cook_more_info_popover`

Are they related to ad filtering or is it an error?

As for the obisk.net website, I see that ads on the site are filtered by the SVN list, but this website also offers web tracking services and should therefore be on the anti-tracking/privacy-enabling lists. The question remaining now is if the SVN list also filters tracking services or should they be submitted to aforementioned anti-tracking lists such as Fanboy's? What if the small local tracking service such as obisk.net is not accepted on these lists?

And last but not least, how would you block the requests to obisk.net (or any other tracking service) without using the third-party directive? For example, EasyPrivacy and Fanboy's ETL have 10-30% third-party rules... and I see that you don't use them, but could you elaborate a bit on it? What's more clean than to block cross-site references if the sites are "bad"?

**Comment by betterwebleon** [comment]
You're right, cookie filter rules shouldn't be on the list. Initially, "_I don't care about cookies_" didn't cover these websites properly. So these rules were added temporarily (except for mercator.si - I made a mistake by adding this one). I forgot to erase them after the addon's update.

_About tracking services_
In the beginning, it was meant the way you assumed: the "tracking part" in Slovenian list is there to cover only those rules which are not covered (e.g. are rejected) by Fanboy's ETL. As much as possible should go to and be handled by ETL, because it is a complete and most suitable list. SVN list has therefore been mostly cosmetic.

But after you pointed it out, I've also been thinking that a lot of simple users are most likely not using Fanboy's ETL, since it is often [not selected by default](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters). So third-party rules are now included in the SVN list.

If you are not planning to, I can report these tracking rules to Fanboy as well (for the benefit of all others who don't use the SVN list).

Thank you for all corrections.

**Comment by drws** [comment]
Out of my 4 third-party rules only 1 still applies (aforementioned obisk.net), the following 3 rules are not necessary anymore:

`najsplet.com^$third-party`
`pagerank.si^$third-party`
`stevec.si^$third-party`

About the obisk.net rule, I ask that you submit it to Fanboy ETL this time (it's better that one person overviews it now that we made so many small changes), but I'll post it to both lists from now on.

**Comment by betterwebleon** [comment]
Thanks for help.
SVN list has been cleaned and the rule `obisk.net^$third-party` reported.

**Comment by betterwebleon** [comment]
One more thing only - regarding Fanboys' ETL: I need to [provide an example site](https://forums.lanik.us/viewtopic.php?f=62&t=31523) for obisk.net 3rd-party rule. Do you know any examples?

**Comment by betterwebleon** [comment]
Nevermind, I found one on https://www.nepremicnine.net/
I will report it.

**Pull request merged**
